---

- name: set environment
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ root_db_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "http://localhost:35357/v3"
    OS_IDENTITY_API_VERSION: 3