---

- name: Copy .my.cfg to home user
  template: src=my.cnf.j2 dest=/home/nikotinik/.my.cnf

- name: Copy .my.cfg to root user
  template: src=my.cnf.j2 dest=/root/.my.cnf

- name: Write password to file
  copy: content={{ root_db_password }} dest={{ mysql_password_file }} force=no

- name: Change root password
  command: mysqladmin -u root password '{{ root_db_password }}'
