---

- name: install MariaDB
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-mysqldb
    - python-pymysql

- name: deploy mysql-openstack config
  template: src=99-openstack.cnf.j2 dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
  notify: restart mysql

- name: Change passwords to root user
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
  - 127.0.0.1
  - ::1
  - localhost

- name: Check if MySQL root password changed
  stat: path={{ mysql_password_file }}
  register: p

- debug: msg="MySQL root password is changed"
  when: p.stat.exists

- include: change-root-passwords.yml
  when: p.stat.exists == False