---

- name: install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present

- name: configure user
  rabbitmq_user:
    user: openstack
    password: {{ root_db_password }}
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present