---

- name: Install the OpenStack Neutron
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: deploy neutron config
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: deploy ml2 config
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini

- name: deploy linux-bridge config
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: configure the layer-3 agent
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    section: DEFAULT
    option: interface_driver
    value: neutron.agent.linux.interface.BridgeInterfaceDriver

- name: deploy DHCP agent config
  template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini

- name: deploy metadata agent
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini
  notify:
    - restart nova-api
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart nova-compute
	
- name: Finalize installation
  shell: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head