---

- name: Create a new database with name 'neutron'
  mysql_db:
    name: neutron
    state: present

- name: Grant all for user 'neutron'
  mysql_user: name=neutron host={{ item }} password={{ root_db_password }} priv=neutron.*:ALL,GRANT state=present
  with_items:
  - 127.0.0.1
  - ::1
  - localhost
  - "%"